# File: job-create-catalog.yml
# Job: Cette tâche créé un catalog
# Help: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml

parameters:
  # URL de la composante API Connect Manager
  - name: CICD_APIC_MANAGER_URL
    type: string
  # Clé API de IBM IAM
  - name: CICD_APIC_IAM_APIKEY
    type: string
  # Nom de la ressource type Organisation
  - name: CICD_APIC_RESSOURCE_ORGANIZATION_NAME
    type: string
  # Suffixe du catalogue (dev, uat, prd)
  - name: CICD_APIC_RESSOURCE_CATALOG_NAME_SUFFIX
    type: string
  # Titre du catalogue 
  - name: CICD_APIC_RESSOURCE_CATALOG_TITLE
    type: string
  # Type du catalogue production ou non production
  - name: CICD_APIC_RESSOURCE_CATALOG_TYPE_IS_PRODUCTION
    type: boolean
  # Dossier contenant les fichiers des configurations
  - name: CICD_WORK_SETTINGS_DIR
    type: string

jobs:
  - job: CreateCatalogJob
    displayName: "Création d'un catalogue"
    workspace:
      clean: all
    steps:
      - checkout: self
        clean: true
        fetchTags: true
        fetchDepth: 0
      - template: /templates/tasks/task-apic-configure.yml
      - template: /templates/tasks/task-apic-login.yml
        parameters:
          CICD_APIC_MANAGER_URL: ${{ parameters['CICD_APIC_MANAGER_URL'] }}
          CICD_APIC_IAM_APIKEY: ${{ parameters['CICD_APIC_IAM_APIKEY'] }}
      - template: /templates/tasks/task-apic-create-catalog.yml
        parameters:
          CICD_APIC_MANAGER_URL: ${{ parameters['CICD_APIC_MANAGER_URL'] }}
          CICD_APIC_RESSOURCE_ORGANIZATION_NAME: ${{ parameters['CICD_APIC_RESSOURCE_ORGANIZATION_NAME'] }}
          CICD_APIC_RESSOURCE_CATALOG_NAME_SUFFIX: ${{ parameters['CICD_APIC_RESSOURCE_CATALOG_NAME_SUFFIX'] }}
          CICD_APIC_RESSOURCE_CATALOG_TITLE: ${{ parameters['CICD_APIC_RESSOURCE_CATALOG_TITLE'] }}
          CICD_APIC_RESSOURCE_CATALOG_TYPE_IS_PRODUCTION: ${{ parameters['CICD_APIC_RESSOURCE_CATALOG_TYPE_IS_PRODUCTION'] }}
          CICD_WORK_SETTINGS_DIR: ${{ parameters['CICD_WORK_SETTINGS_DIR'] }}
      - template: /templates/tasks/task-apic-logout.yml
        parameters:
          CICD_APIC_MANAGER_URL: ${{ parameters['CICD_APIC_MANAGER_URL'] }}