# File: job-restore-definitions-produits-api.yml
# Job: Cette tâche restaure les definitions des produits et d'API à partir d'une sauvegarde
# Help: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml

parameters:
  # URL de la composante API Connect Manager
  - name: CICD_APIC_MANAGER_URL
    type: string
  # Clé API de IBM IAM APIC
  - name: CICD_APIC_IAM_APIKEY
    type: string
  # Nom de la ressource type Organisation pour source du backup
  - name: CICD_APIC_RESSOURCE_ORGANIZATION_NAME
    type: string
  # Numéro de build où se trouvent les fichiers json qui seront utilisés pour la restauration
  - name: CICD_APIC_DEFINITION_ID
    type: string
  # Nom de l'organisation cible ou la restauration ce fait
  - name: CICD_APIC_RESSOURCE_ORGANIZATION_NAME_TARGET
    type: string
    default: 'org-ministere-acme-restore'

jobs:
  - job: RestoreProductsAndAPI
    displayName: "Restauration des produits et API"
    workspace:
      clean: all
    steps:
      - checkout: none
      - template: /templates/tasks/task-apic-configure.yml
      - template: /templates/tasks/task-apic-login.yml
        parameters:
          CICD_APIC_MANAGER_URL: ${{ parameters['CICD_APIC_MANAGER_URL'] }}
          CICD_APIC_IAM_APIKEY: ${{ parameters['CICD_APIC_IAM_APIKEY'] }}
      - template: /templates/tasks/task-apic-verify-products-api.yml
        parameters:
          CICD_APIC_MANAGER_URL: ${{ parameters['CICD_APIC_MANAGER_URL'] }}
          CICD_APIC_RESSOURCE_ORGANIZATION_NAME_TARGET: ${{ parameters['CICD_APIC_RESSOURCE_ORGANIZATION_NAME_TARGET'] }}
      - template: /templates/tasks/task-download-pipeline-artifact.yml
        parameters:
          CICD_APIC_DEFINITION_ID: ${{ parameters['CICD_APIC_DEFINITION_ID'] }}
      - template: /templates/tasks/task-apic-read-backup-json.yml
        parameters:
          CICD_APIC_RESSOURCE_ORGANIZATION_NAME: ${{ parameters['CICD_APIC_RESSOURCE_ORGANIZATION_NAME'] }}
      - template: /templates/tasks/task-apic-restore-api.yml
        parameters:
          CICD_APIC_MANAGER_URL: ${{ parameters['CICD_APIC_MANAGER_URL'] }}
          CICD_APIC_RESSOURCE_ORGANIZATION_NAME: ${{ parameters['CICD_APIC_RESSOURCE_ORGANIZATION_NAME'] }}
          CICD_APIC_RESSOURCE_ORGANIZATION_NAME_TARGET: ${{ parameters['CICD_APIC_RESSOURCE_ORGANIZATION_NAME_TARGET'] }}
      - template: /templates/tasks/task-apic-restore-product.yml
        parameters:
          CICD_APIC_MANAGER_URL: ${{ parameters['CICD_APIC_MANAGER_URL'] }}
          CICD_APIC_RESSOURCE_ORGANIZATION_NAME: ${{ parameters['CICD_APIC_RESSOURCE_ORGANIZATION_NAME'] }}
          CICD_APIC_RESSOURCE_ORGANIZATION_NAME_TARGET: ${{ parameters['CICD_APIC_RESSOURCE_ORGANIZATION_NAME_TARGET'] }}
      - template: /templates/tasks/task-apic-logout.yml
        parameters:
          CICD_APIC_MANAGER_URL: ${{ parameters['CICD_APIC_MANAGER_URL'] }}
