openapi: 3.0.1
info:
  description: Ceci est un API d'exemple basé sur la spécification OpenAPI 3.0 dont le nom est Bonjour Québec avec Client Secret.
  version: 1.0.1
  title: Définition d'API Bonjour Québec avec Client Secret
  x-ibm-name: mcn-pggapi-bonjour-quebec-client-secret-api-definition
servers:
  - url: /bonjour-quebec-client-secret/v1
components:
  securitySchemes:
    ApiKeyAuth:
      description: Jeton de type apiKey (clé API).
      in: header
      name: X-QC-Client-Id
      type: apiKey
      x-key-type: client_id
    ClientSecretAuth:
      description: Jeton de type client secret
      in: header
      name: X-QC-Client-Secret
      type: apiKey
      x-key-type: client_secret
paths:
  /hello:
    get:
      responses:
        '200':
          description: success
          content:
            '*/*':
              schema:
                type: string
security:
  - ApiKeyAuth: []
    ClientSecretAuth: []
x-ibm-configuration:
  $ref: mcn-pggapi-bonjour-quebec-ibm-configuration-definition.yaml
