openapi: 3.0.1
info:
  description: Ceci est un API d'exemple basé sur la spécification OpenAPI 3.0 dont le nom est Bonjour Québec.
  version: 1.0.1
  title: Définition d'API Bonjour Québec
  x-ibm-name: org-acme-bonjour-quebec-api-definition
servers:
  - url: /bonjour-quebec/v1
components:
  securitySchemes:
    ApiKeyAuth:
      description: Jeton de type apiKey (clé API).
      in: header
      name: X-QC-Client-Id
      type: apiKey
      x-key-type: client_id
paths:
  /hello:
    get:
      responses:
        '200':
          description: success
          content:
            '*/*':
              schema:
                type: string
security:
  - ApiKeyAuth: []
x-ibm-configuration:
  $ref: org-acme-bonjour-quebec-ibm-configuration-definition.yaml
