# File: task-archive-files.yml
# Task: Cette tâche Zip des fichiers de backup

parameters:
  # Nom de la ressource type Organisation
  - name: CICD_APIC_RESSOURCE_ORGANIZATION_NAME
    type: string

steps:
  - task: ArchiveFiles@2
    displayName: 'Zip des fichiers de backup'
    condition: succeededOrFailed()
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)/provider_orgs
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: $(Build.ArtifactStagingDirectory)/backup-organization-${{ parameters['CICD_APIC_RESSOURCE_ORGANIZATION_NAME'] }}.zip
      replaceExistingArchive: true
