# File: pipeline-create-catalog.yml
# Pipeline: Ce pipeline créé un catalog
# Help: https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops

# Set build number format in semver
name: $(Date:yyyy).$(Date:MMdd).$(DayOfYear)$(Rev:rr)_${{ parameters['CICD_APIC_RESSOURCE_ORGANIZATION_NAME'] }}-cat-${{ parameters['CICD_APIC_RESSOURCE_CATALOG_NAME_SUFFIX'] }}

# Set triggers
trigger: none

# Set pools
pool: Default

# Set parameters
# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script
parameters:
  # Nom de la ressource type Organisation
  - name: CICD_APIC_RESSOURCE_ORGANIZATION_NAME
    type: string
    default: 'org-acme'
  # Suffixe de la ressource type Catalogue
  - name: CICD_APIC_RESSOURCE_CATALOG_NAME_SUFFIX
    type: string
    default: 'dev'
  # Titre de la ressource type Catalogue
  - name: CICD_APIC_RESSOURCE_CATALOG_TITLE
    type: string
    default: 'Développement'
  # Type du catalogue production ou non production
  - name: CICD_APIC_RESSOURCE_CATALOG_TYPE_IS_PRODUCTION
    type: boolean
    default: true
  # Nom du groupe de variables pour garder le secret APIC_IAM_APIKEY cible pour ce pipeline
  - name: CICD_SECRETS_APIC_IAM_APIKEY
    type: string
    default: 'org-acme-acg-admin'

# Set variables
# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch
variables:
  - name: APIC_MANAGER_URL
    value: "https://api.4ef0-67e5d910.ca-tor.ri.apiconnect.cloud.ibm.com"
  # Nom du groupe de variables pour garder le secret cible pour ce pipeline
  - group: ${{ parameters['CICD_SECRETS_APIC_IAM_APIKEY'] }}
# - name: APIC_IAM_APIKEY
#   value: "*****"

# Set stages
# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace
stages:
  - stage: "CD_CreateCatalog"
    displayName: "Création du catalogue"
    jobs:
      - template: /templates/jobs/job-create-catalog.yml
        parameters:
          CICD_APIC_MANAGER_URL: ${{ variables['APIC_MANAGER_URL'] }}
          CICD_APIC_IAM_APIKEY: $(APIC_IAM_APIKEY)
          CICD_APIC_RESSOURCE_ORGANIZATION_NAME: ${{ parameters['CICD_APIC_RESSOURCE_ORGANIZATION_NAME'] }}
          CICD_APIC_RESSOURCE_CATALOG_NAME_SUFFIX: ${{ parameters['CICD_APIC_RESSOURCE_CATALOG_NAME_SUFFIX'] }}
          CICD_APIC_RESSOURCE_CATALOG_TITLE: ${{ parameters['CICD_APIC_RESSOURCE_CATALOG_TITLE'] }}
          CICD_APIC_RESSOURCE_CATALOG_TYPE_IS_PRODUCTION: ${{ parameters['CICD_APIC_RESSOURCE_CATALOG_TYPE_IS_PRODUCTION'] }}
          CICD_WORK_SETTINGS_DIR: "$(Build.SourcesDirectory)/templates/pipelines/settings"